# Generated by Django 5.0.1 on 2024-02-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_management', '0002_alter_student_name_alter_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default=float, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
