# Generated by Django 5.0.1 on 2024-02-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_management', '0003_student_surname_teacher_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
