# Generated by Django 5.0.1 on 2024-02-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_management', '0004_alter_student_surname_alter_teacher_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
