# Generated by Django 5.0.1 on 2024-02-03 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_management', '0005_remove_student_grade_remove_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule_management.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule_management.subject'),
            preserve_default=False,
        ),
    ]
